### ISSUE TITLE
Mocking IXMLHTTPRequest2?

### ISSUE THREAD

**Issue by pps83** [Microsoft/libHttpClient#154]
One of the goals of the project is "Built-in API support to switch to mock layer".
I'm curious how you could mock IXMLHTTPRequest2 if it's so extremely limited or even broken at times (getting headers when handling redirects for example). I'm actually working on a very similar effort as `libHttpClient` and I simply cannot mock most of the stuff with IXMLHTTPRequest2. For example, I want to unit test some requests/results to/from facebook.com. Either I'd need to change host name to something else or setup dns override (which is nonsense) to be able to mock dns resolution. So, how are you planning to mock it with IXMLHTTPRequest2? Or you mock everything with different code completely which might leave IXMLHTTPRequest2-based impl untested?

I wish xbox didn't have that nonsense requirement to use this broken api in the first place so I could delete IXMLHTTPRequest2-based implementation and never hear about it again.

**Comment by jasonsandlin** [comment]
Yeah that makes sense.  Our primary tests are to ensure that the Xbox Live services respond correctly (via XSAPI) regardless of the http backend we are using.

But if you want to mock on Xbox in the pattern your doing, if you have access to the XDK, you might be able to do https://docs.microsoft.com/en-us/windows/uwp/xbox-live/using-xbox-live/troubleshooting/how-to-set-up-fiddler-for-debugging#for-xbox-one-xdk-based-projects and then instead of using Fiddler, setup a http server.  Not sure.  Never tried it.  Alternatively I know you can use Fiddler auto-responders but its more limited than your own http server code.
