### ISSUE TITLE
HCGetWebSocketConnectResult populates result with different handle

### ISSUE THREAD

**Issue by redbaron** [microsoft/libHttpClient#697]
`HCGetWebSocketConnectResult ` seems to populate result with a different websocket handle than one used to call HCWebSocketConnectAsync.  When multiple simultaneous connections are used I wanted to use `WebSocketCompletionResult::websocket`  to disambiguate between them, but it seems not possible.

```
auto* asyncBlock = new XAsyncBlock{};
asyncBlock->context = ws;
asyncBlock->queue = q;
asyncBlock->callback = [](XAsyncBlock *ab) {
    const std::unique_ptr<XAsyncBlock> asyncBlock(ab);
    auto ws = static_cast<HCWebsocketHandle>(asyncBlock->context);

    WebSocketCompletionResult result{};
    HRESULT hr = HCGetWebSocketConnectResult(asyncBlock.get(), &result);
    if (SUCCEEDED(hr)) {
       assert(ws == result.websocket);  // <<< FAILS
    }
};

HCWebSocketConnectAsync(URL, "",  ws, asyncBlock);
```

**Comment by jplafonta** [comment]
You are correct, this was somewhat intentional.  After calling HCWebSocketConnectAsync, the internal WebSocket object will be kept alive by libHttpClient until it is disconnected - even if the client closes their handle.  The handle populated in the result is guaranteed to be a valid handle to the WebSocket, while the client's handle isn't.

In theory, you should be able to disambiguate between which WebSocket is connection is completing based on the XAsync context, but I also recognize that using the returned handle would be easier/more intuitive.  I will change this to pass back the client's handle as part of the connect result, but the library still makes no guarantees that the handle is valid as it's still owned by the client.

**Comment by redbaron** [comment]
In actual app context is already taken by `this` :) Your plan to change to pass handle used in connect call is very welcome. It will also make on connect callback more alike rest of callbacks on the websocket.

**Comment by jplafonta** [comment]
Client's handle will now be returned in the async result after this change: https://github.com/microsoft/libHttpClient/pull/699
