### ISSUE TITLE
How to use with Xbox Durango XDK

### ISSUE THREAD

**Issue by zacharyneveu** [microsoft/libHttpClient#784]
Hi, I'm looking to use this from a DLL built against an old Durango XDK for Xbox One. Does the XDK ship with a pre-compiled version of libHttpClient somewhere? If not, any tips on how to build this library with the XDK? Alternatively, is there a different recommended library for basic web requests in the XDK? For modern GDK I use Xcurl, but that doesn't exist in the older XDKs.

**Comment by jasonsandlin** [comment]
XDK support was removed recently but you can use an older release such as 2306: https://github.com/microsoft/libHttpClient/tree/preview/2306/Build.  

See folders named *XDK*.  Open the 2015/2017/2019 SLN in the root and build the XDK project

**Comment by zacharyneveu** [comment]
Appreciate the link, that's very helpful.

In particular, we're looking to build against XDK version 140703 which uses v110 build tools and Visual Studio 2012. Going back through old releases I'm not sure if this was ever supported for `libHttpClient`. Any idea how hard it would be to get this working or how hard it would be?

Given the potential difficulty, we're also looking into the possibility of using `IXMLHttpRequest2`. Does that sound like a better option given our XDK version? Are there other alternatives that you would recommend? We're just looking for basic post/get functionality, no need for exotic protocols, web sockets etc.

**Comment by jasonsandlin** [comment]
I assume you mean 1807?  

You can look through the project tags but the oldest platform toolset we supported in libhttpclient was v140 which is Visual Studio 2015.  You can certainly try to make it work, but you'll probably hit complex build errors.  You might want to build it in VS2017, etc and just output a DLL and link to that.  Just flip the project setting to build a DLL instead of static lib.  That might be a lot easier to do.  Might need to mess with a .def file, etc.   Also I recommend you don't use source that's more than a year old there's been a lot of bug fixes since early days of the project of course.

Another option is to use cpprestsdk instead.  Go here: https://github.com/microsoft/xbox-live-api/tree/1807_xdk_qfe16 and follow the External folder into the submodule for cpprestsdk which leads to my fork which has a casablanca110.Xbox.sln.  Back in the XDK days we used cpprestsdk since libHttpClient wasn't around.
